# Site settings
title: Playlab tech blog
description: >
  Playlab is a leading game developer & publisher that has grown from a handful
  of passionate gamers to a group of 80 and more enthusiasts striving to create
  the best games for iOS and Android devices along with Facebook.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pocket-playlab.github.io" # the base hostname & protocol for your site
facebook_username: PlaylabGames
twitter_username: PlaylabGames
github_username:  pocket-playlab

# Build settings
markdown: kramdown
